vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        videos_upload:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/public/uploads/videos'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            delete_on_remove: true
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#        media_object:
#        uri_prefix: /media
#        upload_destination: '%kernel.project_dir%/public/media'
