api_platform:
    resource: .
    type: api_platform
    prefix: /api

#video_upload:
#    path: /api/videos
#    controller: App\Controller\VideoUploadController::class
#    methods: POST

create_manufacturer:
    path: /api/manufacturer
    controller: App\Controller\ManufacturerController
    methods: POST
